### ISSUE TITLE
Would it be possible to support GLOBs/wildcard for PUTs?

### ISSUE THREAD

**Issue by dav1dc-pcf** [pivotal-cf/azure-blobstore-resource#10]
Would it be possible to support GLOBs/wildcards for resource PUTs?

Currently in order to PUT a file to this azure blob store resource, we have to call out the entire filename explicitly. Even the simplest GLOBs/regex fails with an unable to find file error.

**Comment by christianang** [comment]
I've implemented the `regexp` param and added GLOB support in the file param for `put`. So using snapshots for versioning is no longer required. Reopen the issue if I've missed something.
