### ISSUE TITLE
consider upgrading dependencies to latest stable

### ISSUE THREAD

**Issue by eitansuez** [pivotal-cf/azure-blobstore-resource#18]
see [my Gopkg.toml](https://github.com/eitansuez/azure-blobstore-resource/blob/master/Gopkg.toml) for the recipe.

this brings ginkgo, gomega, and azure-sdk-for-go up to latest stable version.

the override of fsnotify is a known issue with dep.

the override of opencensus-proto has to do with incorrect dependency version between two transitive dependencies.

**Comment by christianang** [comment]
Done. Thanks for looking into the various issues with upgrading too. 💯
