### ISSUE TITLE
consider implementing download/upload in terms of azure-storage-blob-go sdk

### ISSUE THREAD

**Issue by eitansuez** [pivotal-cf/azure-blobstore-resource#19]
it appears microsoft has an sdk dedicated to storing all types of blobs (block blobs etc..).
see https://github.com/Azure/azure-storage-blob-go

it might be more performant, and delegate more of the details of the download/upload operation to the sdk, where it likely belongs.

**Comment by christianang** [comment]
Merged the PR manually.
