### ISSUE TITLE
Occaisionally panics due to upstream bug

### ISSUE THREAD

**Issue by svrc-pivotal** [pivotal-cf/azure-blobstore-resource#23]
This will SIGSEV on download under some circumstances, I suspect due to this issue:
https://github.com/Azure/azure-storage-blob-go/issues/134

This I believe is fixed in 0.7.0 of the upstream.  Going to try to build a custom fork of this with the new dependency to validate.

**Comment by christianang** [comment]
Thanks for letting me know. Let me know if you validate this, otherwise I'll look into this and bump the dependency whenever I get a chance.

**Comment by christianang** [comment]
Bumped azure-storage-blob-go to 0.7.0. Closing.
