### ISSUE TITLE
File uploads fail over 195G

### ISSUE THREAD

**Issue by a-bardai** [pivotal-cf/azure-blobstore-resource#25]
We are trying to upload files to the blob store that are over 195 G and they are failing with a message of 'block list is over 50,000'. Seems like the 4M limit on the chunk size only applied to the REST version < 2016-05-31. The Rest versions after that supports chunk size up to 100M. The current service version used by 'Azure/azure-storage-blob-go' is 2018-11-09. Can we make the chunk size in 'azure-blobstore-resource/azure/client.go' configurable or just be set to 100M?
We are using this through Concourse's azure-blobsotre resource-type, which uses the 'pcfabr/azure-blobstore-resource' docker image.

**Comment by christianang** [comment]
Sounds like a reasonable thing to make configurable. I think I'll keep the default at 4M to keep the memory usage low for the resource.

**Comment by luckyinfil** [comment]
Just ran into this issue as well. +1 for making it configurable!

**Comment by christianang** [comment]
I've added this and cut a new version. There is now a `block_size` param for In and Out. Try it out and feel free to reopen the issue you run into any issues.
