### ISSUE TITLE
Issue with sub-microseconds digit in snapshot timestamps

### ISSUE THREAD

**Issue by bgandon** [pivotal-cf/azure-blobstore-resource#27]
Hi,

Our pipelines are blocked because when the last 7th digit is `0` the resource omits it, whereas Azure is expecting it.

Example:
- The Azure blobstore resources creates a `terraform.tfstate?snapshot=2019-10-23T14:40:22.186881Z` snapshot.
- Azure stores `2019-10-23T14:40:22.1868810Z` as the snapshot timestamp, please note the last `0`, right before `Z`, that seems to be added by Azure.
- When the resource tries to access this snapshot, it uses `2019-10-23T14:40:22.186881Z` as the timestamp, but Azure is expecting the last `0` digit to be specified, so an error `400` is returned because the timestamp is deemed invalid by Azure.

The resulting error is:
```
2019/10/23 15:43:07 failed to copy blob: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=) =====
Description=400 Value for one of the query parameters specified in the request URI is invalid., Details: (none)
   HEAD https://<redacted>.blob.core.windows.net/terraform/terraform.tfstate?snapshot=2019-10-23T14%3A40%3A22.186881Z&timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.7 (go1.13.3; linux)]
   X-Ms-Client-Request-Id: [2f79966f-02b2-4382-47ba-9f0083c91dca]
   X-Ms-Date: [Wed, 23 Oct 2019 15:43:07 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Value for one of the query parameters specified in the request URI is invalid.
   Date: [Wed, 23 Oct 2019 15:43:07 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [afa3f0b9-601e-0000-30b8-891dd2000000]
```

When the last digit of the timestamp is not `0`, then the resource succeeds at downloading the snapshot.

The issue is the same when storing a new version. Whenever the last digit is `0`, it fails, and whenever it is not `0` it succeeds.

Cloud you please push a fix as soon as possible, because our pipelines are experiencing big flaky errors with this issue.

Best,
Benjamin

**Comment by christianang** [comment]
Good find. This is fixed in the latest image. Feel free to reopen if the issue persists.
