### ISSUE TITLE
When unarchiving, the CLIs handle edge cases with symlinks

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/azure-blobstore-resource#33]
When we had an issue with the GCS resource (the user could not unarchive our docker image properly), we investigated.
It turned out that the resource was using the golang libraries for tar and zip.
The libraries are helpful, but it turned out they did not handle edge cases with symlinks.

We made a [PR](https://github.com/frodenas/gcs-resource/pull/22) to the GCS resource to have it use the CLIS.
We did try to use the `archiver` library in golang, but it could not handle the symlinks.
The PR follows the [same patterns](https://github.com/concourse/s3-resource/blob/master/in/archive.go) done by the native s3-resource.

**Comment by christianang** [comment]
This has been fixed in [v0.8.0](https://github.com/pivotal-cf/azure-blobstore-resource/releases/tag/v0.8.0).
