### ISSUE TITLE
Resource produces duplicate Concourse versions for the same blob

### ISSUE THREAD

**Issue by crusstu** [pivotal-cf/azure-blobstore-resource#44]
Hi there :wave: I'm not entirely sure if this is known/expected behaviour and someone can correct my usage of the resource or if this actually a bug, but I've noticed that the `azure-blobstore-resource` seems to be producing duplicate Concourse resource versions for the same blob. This is an issue for me because some of my jobs are set up to `trigger: true` on new blob versions, but sometimes they get stuck looking for the newest versions that satisfy my `passed` criteria and don't trigger as expected.

In my pipeline I take in a blob from another source and `put` it to an Azure blobstore container via the resource to keep a copy of the blob I can manage myself instead of relying on the original source to be available. Later on in the same pipeline I `get` the blob using the same `azure-blobstore-resource` instance I `put`ted to earlier and do some work with it. When I look at the versions produced by the `azure-blobstore-resource` I can see 2 resource versions for the same blob:

![image](https://user-images.githubusercontent.com/61292541/130501019-6a6b8f7a-1f7d-45f3-8dd5-ddffc36104c8.png)

One has just the `path` field and the other has `path` and `version`. Both of the `path`s are the same and refer to the same blob, but it looks like because the second resource version has the additional `version` field Concourse treats them as 2 separate resource versions.

I had a quick look over the implementation and it looks like in the `out` script it produces new Concourse resource versions with just the `path` field (I'm using regexes, not blobstore snapshots):

https://github.com/pivotal-cf/azure-blobstore-resource/blob/0b0c7277cf6b0a9ca3bf04398793ae49d3c8f8b5/cmd/out/main.go#L80-L84

but the `check` script produces new Concourse resource versions with a `path` and a `version`:

https://github.com/pivotal-cf/azure-blobstore-resource/blob/0b0c7277cf6b0a9ca3bf04398793ae49d3c8f8b5/api/check.go#L152-L156

Unless I'm not using the resource correctly, I would expect to see only 1 resource version for a given blob.

**Comment by christianang** [comment]
That does look like a bug. I think you are correct in that the out should be outputting the `version` as well, not just the `path` and that is what you are seeing in your screenshot.

I think this will need to do something similar to check to use the regexp to pull out the version from the path and add that to the response.

Adding a `help wanted` label, would love to see you or someone else PR this in.
