### ISSUE TITLE
Directories not supported

### ISSUE THREAD

**Issue by mlapointe22** [pivotal-cf/azure-blobstore-resource#6]
Specifying a `versioned_file` blob inside a logical directory currently breaks the get (in) operation.

YAML Specified:
versioned_file: platform-automation/0.0.1-rc.248/platform-automation-0.0.1-rc.248-tasks.zip

Error Output:
2018/11/09 19:50:42 failed to copy blob: open /tmp/build/get/platform-automation/0.0.1-rc.248/platform-automation-0.0.1-rc.248-tasks.zip: no such file or directory

Putting the blob at the container root fixes the error.

**Comment by christianang** [comment]
Fixed in the latest image.
