### ISSUE TITLE
Would it be possible to support unpacking blobs similar to S3?

### ISSUE THREAD

**Issue by iamtpage** [pivotal-cf/azure-blobstore-resource#7]
The S3 Concourse supports unpacking blobs (`unpack: true`) as part of `in`, would it be possible to do the same here? The code is already written and would just have to be ported to support Azure blobstore: https://github.com/concourse/s3-resource/blob/master/in/archive.go

**Comment by christianang** [comment]
This sounds useful, but given my limited time to work on this resource I'm going to open this up to others to PR.

**Comment by christianang** [comment]
The `unpack` param on `in` has been implemented and is near feature parity with the s3 resource. Currently, supports tar, zip, gzip files similar to s3. I haven't implemented support for gzipped tarballs yet and will get to it at a later date, but 90% of the way there.

**Comment by christianang** [comment]
`.tar.gz` files are now supported with `unpack` so this have parity with the s3 resource (506ce413774b336b5336dde324b5f69892ab5325).

Closing.
